<!DOCTYPE html>
<html lang="en-US">
<!--********************************************-->
<!--*       Generated from PreTeXt source      *-->
<!--*                                          *-->
<!--*         https://pretextbook.org          *-->
<!--*                                          *-->
<!--********************************************-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="robots" content="noindex, nofollow">
</head>
<body class="ignore-math">
<h4 class="heading"><span class="type">Paragraph</span></h4>
<div class="para">To detect a thrown exception, embed all statements in a <dfn class="terminology">try-block</dfn>. To catch exceptions thrown from code in a try-block, follow the try-block with one or more <dfn class="terminology">catch-blocks</dfn>. Consider the following updated sample program in <a href="" class="xref" data-knowl="./knowl/listing-ex-try.html" title="Listing 11.3.2">ListingÂ 11.3.2</a>, with a try-catch statement added.</div>
<span class="incontext"><a href="section-ex-catching.html#p-850" class="internal">in-context</a></span>
</body>
</html>
